---
apiVersion: edge.kubestellar.io/v1alpha1
kind: Location
metadata:
  name: dev
  labels:
    env: dev
spec:
  instanceSelector:
    matchLabels:
      env: dev
  resource:
    group: edge.kubestellar.io
    resource: synctargets
    version: v1alpha1
